### ISSUE TITLE
Issiue with article loading

### ISSUE THREAD

**Issue by JuergenS64** [aggrosoft/oxid-variant-selection-icons#1]
Hello Aggrosoft,
at first, great Modul.

I found a problem:
As an example I have an article combination with color and lettering
If you select the "Label" option, the line with the text input is not displayed/loaded.

Best regards

Jürgen

**Comment by kingschnulli** [comment]
Could you please add a Screenshot or a link where this Problem occurs? Or please explain a little more detailed.

**Comment by JuergenS64** [comment]
Hello Aggrosoft,
the explanation was a little short.
First, create an article for customization.
Products -> Extended -> "Product can be customized".
Create the variation "with labeling" and "without labeling".
In my case, the item is also available in different colors.
If you normally select the item for customization (without your module), a field will appear in which you can enter individual text.

If the module is activated and I choose the option "with labeling", the input field does not appear.
I hope my explanation is better now.

With kind regards

Jürgen

**Comment by kingschnulli** [comment]
Which Version and template are you using? Have you customized your theme?

**Comment by JuergenS64** [comment]
I am using Oxid CE Version 6.1.5 with wave theme, without any change.

**Comment by JuergenS64** [comment]
Hello Aggrosoft,
i don't know what was happens.
Tmp- and session-Files was deleted, Browser-Cache also deleted.
Now i have installed it again and now it works?!?
I can't reproduce it.
If possible please delete the thread.
The Module is super
Best Regards
Jürgen
